# Generated by Django 6.0.3 on 2026-03-09 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True)),
                ('preferences', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('total_score', models.FloatField(default=0)),
                ('total_quizzes', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('show_on_leaderboard', models.BooleanField(default=True)),
                ('streak', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
