# Generated by Django 6.0.3 on 2026-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_topic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
