# Generated by Django 6.0.3 on 2026-03-14 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_questionattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attempted_users',
            field=models.ManyToManyField(blank=True, related_name='attempted_questions', through='quiz.QuestionAttempt', to=settings.AUTH_USER_MODEL),
        ),
    ]
