# Generated by Django 6.0.3 on 2026-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_attempted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
